# Generated by Django 6.0.4 on 2026-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='SoloStore', max_length=200)),
                ('tagline', models.CharField(default='Your One-Stop Store', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('email', models.EmailField(default='info@SoloStore.com', max_length=254)),
                ('phone', models.CharField(default='+880 1234-567890', max_length=30)),
                ('address', models.CharField(default='Dhaka, Bangladesh', max_length=300)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('banner_title', models.CharField(default='Shop Smarter, Live Better', max_length=200)),
                ('banner_subtitle', models.TextField(default='Discover thousands of quality products — delivered fast, priced right.')),
                ('footer_text', models.CharField(default='Your trusted one-stop shop for quality products at amazing prices.', max_length=500)),
                ('copyright_text', models.CharField(default='© 2026 SoloStore. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='📦', help_text='Emoji or icon class for display', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Percentage discount (0-100). Overridden by discount_price if set.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discounted price. Leave blank for no discount.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage for all products in this flash sale (e.g. 30 = 30% off)')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('banner_color', models.CharField(default='#ff6584', help_text='Banner background color (hex code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='flash_sales', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
