# Generated by Django 6.0.4 on 2026-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Product details/specifications. Enter each detail on a new line. Each line will appear as a bullet point.'),
        ),
    ]
