# Generated by Django 6.0.4 on 2026-07-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price of the product (for calculating expense and profit).', max_digits=10),
        ),
    ]
